
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-10-02 14:47:28.221435
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
PortManager_BASEDIR := $(BASEDIR)PortManager
Forwarding_BASEDIR := $(BASEDIR)Forwarding


ALL_MODULES := $(ALL_MODULES) Forwarding PortManager
